"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Crosshair, Expand, Layers3, MousePointer2, Rotate3D, Sparkles } from "lucide-react";
import { motion } from "motion/react";
import { components } from "@/data/components";
import { ViewerProvider } from "@/stores/viewer-store";
import { ModelViewport } from "@/components/three/model-viewport";
import { PreviewGallery } from "@/components/three/preview-gallery";
import { Eyebrow } from "@/components/ui/primitives";
import { ManufacturingJourney } from "@/features/manufacturing/manufacturing-journey";
const featured = components[0];
function Initialization({ ready }: { ready:boolean }) {
  const [show,setShow] = useState(false);
  const [phase,setPhase] = useState(0);
  useEffect(() => { const frame = requestAnimationFrame(() => { if(!sessionStorage.getItem("mechavis-initialized")) {setShow(true);setPhase(1);} }); const step = setTimeout(() => setPhase(2),180); const limit = setTimeout(() => setShow(false),5000); return () => {cancelAnimationFrame(frame);clearTimeout(step);clearTimeout(limit);}; },[]);
  useEffect(() => { if(!ready) return; const frame = requestAnimationFrame(() => setPhase(3)); const exit = setTimeout(() => { setShow(false); sessionStorage.setItem("mechavis-initialized","1"); },350); return () => {cancelAnimationFrame(frame);clearTimeout(exit);}; },[ready]);
  if(!show) return null;
  return <div className="initialization"><div className="boot-mark">M/</div><h2>MECHAVIS</h2><span className="eyebrow">DIGITAL ENGINEERING LAB</span><div className="boot-lines">{["Initializing geometry engine...","Loading engineering data...","Calibrating visualization..."].map((text,i) => <div key={text} className={i < phase ? "complete" : ""}><span>{text}</span><span>{i < phase ? "OK" : "—"}</span></div>)}</div><div className="boot-progress"><span style={{width:`${Math.round(phase/3*100)}%`}}/></div><span className="mono">{Math.round(phase/3*100)}%</span></div>;
}
export function LabHome() {
  const [ready,setReady] = useState(false);
  const onReady = useCallback(() => setReady(true),[]);
  return <div className="lab-home"><Initialization ready={ready}/><section className="lab-hero"><div className="hero-topline"><Eyebrow><span className="status-dot"/> INTERACTIVE ENGINEERING ENVIRONMENT</Eyebrow><span className="mono muted">LAB.001 / EXPLORE MODE</span></div><div className="hero-scene"><ViewerProvider><ModelViewport component={featured} hero onReady={onReady}/></ViewerProvider><div className="scanner-line" aria-hidden="true"/></div><motion.div className="hero-copy" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:0.7}}><div className="hero-edition"><span>BEYOND THE BLUEPRINT</span><span>01 — 10</span></div><h1>MECHAVIS<span className="accent">®</span></h1><h2>Digital<br/>Engineering Lab<span className="accent">.</span></h2><p>Explore the geometry, materials and behavior of mechanical components in an interactive digital environment.</p><div className="hero-actions"><Link href="/components" className="button">Explore components <ArrowUpRight size={16}/></Link><Link href="/components/input-shaft" className="text-button">Enter the lab <ArrowRight size={15}/></Link></div><div className="hero-capabilities"><span><Rotate3D size={12}/> REAL-TIME 3D</span><i/><span><Sparkles size={12}/> AI-POWERED INSIGHTS</span></div></motion.div><div className="hero-callout top"><span className="callout-line"/><span className="eyebrow">01 / PRECISION GROUND</span><strong>Bearing journal</strong><span>Ra 0.8 μm</span></div><div className="hero-callout bottom"><span className="callout-line"/><span className="eyebrow">02 / TORQUE TRANSFER</span><strong>Involute spline</strong><span>AISI 4140 · 28–32 HRC</span></div><div className="hero-model-label"><span className="part-label"><Crosshair size={15}/> FEATURED COMPONENT</span><Link href="/components/input-shaft">Input Shaft Assembly <ArrowUpRight size={15}/></Link><span className="mono">IS-1042 / TRANSMISSION SYSTEM</span></div><div className="hero-bottomline"><span><MousePointer2 size={12}/> DRAG TO ROTATE <i/> SCROLL TO ZOOM</span><span><span className="status-dot"/> LIVE RENDER <span className="muted">/ PERSPECTIVE</span></span></div></section>
    <section className="hero-data-strip" aria-label="Featured component specifications">{[{label:"PART NUMBER",value:"IS-1042"},{label:"MATERIAL",value:"AISI 4140"},{label:"PROCESS",value:"CNC + GRINDING"},{label:"TOLERANCE",value:"±0.02 mm"},{label:"STATUS",value:"INSPECTED"}].map((item,i) => <div key={item.label}><span>{item.label}</span><strong>{i === 4 && <span className="status-dot"/>}{item.value}</strong></div>)}</section>
    <section className="discovery-section"><div className="discovery-heading"><div><Eyebrow><span className="tiny-square"/> THE COMPONENT LIBRARY</Eyebrow><h2>Every detail has a purpose<span className="accent">.</span></h2><p>Explore the engineering behind the component.</p></div><Link href="/components" className="text-button">View all components <span className="count-label">10</span><ArrowUpRight size={15}/></Link></div><PreviewGallery items={components.slice(0,3)} renderItem={(c,preview) => <Link href={`/components/${c.id}`} className="component-card" key={c.id}><div className="card-topline"><span>{c.partNumber}</span><ArrowUpRight size={16}/></div>{preview}<div className="component-card-bottom"><span className="eyebrow">{c.category}</span><h3>{c.name}</h3><div><span>{c.material.name}</span><span className="card-open">EXPLORE <ArrowRight size={12}/></span></div></div></Link>}/></section>
    <section className="lab-philosophy"><div className="philosophy-index">/ 02</div><div><Eyebrow>UNDERSTAND. NOT JUST OBSERVE.</Eyebrow><h2>A closer look.<br/>A deeper understanding.</h2></div><div className="philosophy-details"><p>From a micron-level surface finish to the material that carries the load. Go beyond what a component looks like. Discover why it works.</p><div><span><Layers3 size={17}/> Explore every layer</span><span><Expand size={17}/> Take the assembly apart</span><span><Sparkles size={17}/> Ask the right questions</span></div><Link href="/ai" className="text-button">Meet your engineering assistant <ArrowUpRight size={15}/></Link></div></section>
    <ManufacturingJourney component={featured}/><div className="lab-endnote"><ArrowDown size={14}/><span>BUILT FOR CURIOSITY. ENGINEERED FOR UNDERSTANDING.</span><span>ILLUSTRATIVE ENGINEERING ENVIRONMENT</span></div>
  </div>;
}
